apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter
  namespace: kube-system
  labels:
    component: blackbox-exporter
spec:
  type: ClusterIP
  ports:
  - name: probe
    port: 9115
    protocol: TCP
  selector:
    component: blackbox-exporter
