{{- if .Values.enabled }}
apiVersion: {{ include "podsecuritypolicyversion" .}}
kind: PodSecurityPolicy
metadata:
  name: gardener.kube-system.csi-attacher
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  privileged: false
  volumes:
  - hostPath
  hostNetwork: false
  allowedHostPaths:
{{- if semverCompare ">= 1.13" .Values.kubernetesVersion }}
  - pathPrefix: /var/lib/kubelet/plugins/diskplugin.csi.alibabacloud.com
{{- else }}
  - pathPrefix: /var/lib/kubelet/plugins/csi-diskplugin
{{- end }}
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  readOnlyRootFilesystem: false
{{- end -}}
