{{- if .Values.enabled }}
apiVersion: {{ include "podsecuritypolicyversion" .}}
kind: PodSecurityPolicy
metadata:
  name: gardener.kube-system.csi-snapshotter
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  privileged: false
  volumes:
  - hostPath
  hostNetwork: false
  allowedHostPaths:
  - pathPrefix: /var/lib/kubelet/plugins/diskplugin.csi.alibabacloud.com
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  readOnlyRootFilesystem: false
{{- end -}}
