{{- if .Values.enabled }}
apiVersion: {{ include "podsecuritypolicyversion" .}}
kind: PodSecurityPolicy
metadata:
  name: gardener.kube-system.csi-disk-plugin-alicloud
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  privileged: true
  allowPrivilegeEscalation: true
  volumes:
  - hostPath
  - secret
  hostNetwork: true
  allowedHostPaths:
{{- if semverCompare ">= 1.13" .Values.kubernetesVersion }}
  - pathPrefix: /var/lib/kubelet
  - pathPrefix: /dev
{{- else }}
  - pathPrefix: /var/lib/kubelet/plugins/csi-diskplugin
  - pathPrefix: /var/lib/kubelet/plugins/kubernetes.io/csi/pv
  - pathPrefix: /var/lib/kubelet/pods
  - pathPrefix: /dev
  - pathPrefix: /run/dbus
  - pathPrefix: /sys
  - pathPrefix: /lib/modules
{{- end -}}
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  readOnlyRootFilesystem: false
{{- end -}}
