{{- if .Values.enabled }}
apiVersion: {{ include "podsecuritypolicyversion" .}}
kind: PodSecurityPolicy
metadata:
  name: gardener.kube-system.csi-plugin
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  privileged: true
  allowPrivilegeEscalation: true
  volumes:
  - hostPath
  - secret
  hostNetwork: true
  allowedHostPaths:
  - pathPrefix: /var/lib/kubelet/plugins/csi-diskplugin
  - pathPrefix: /var/lib/kubelet/pods
  - pathPrefix: /dev
  - pathPrefix: /run/dbus
  - pathPrefix: /sys
  - pathPrefix: /lib/modules
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  readOnlyRootFilesystem: false
{{- end -}}
