apiVersion: {{ include "rbacversion" . }}
kind: ClusterRole
metadata:
  name: garden.sapcloud.io:psp:unprivileged
rules:
- apiGroups:
  - policy
  - extensions
  resourceNames:
  - gardener.unprivileged
  resources:
  - podsecuritypolicies
  verbs:
  - use
