---
apiVersion: v1
kind: Secret
metadata:
  name: internal-domain-unmanaged
  namespace: garden
  labels:
    garden.sapcloud.io/role: internal-domain
  annotations:
    # dns.garden.sapcloud.io labels are deprecated and will be removed in a future version
    dns.garden.sapcloud.io/provider: unmanaged
    dns.garden.sapcloud.io/domain: nip.io
    dns.gardener.cloud/provider: unmanaged
    dns.gardener.cloud/domain: nip.io
type: Opaque
