---
apiVersion: controllermanager.config.gardener.cloud/v1alpha1
kind: ControllerManagerConfiguration
clientConnection:
  acceptContentTypes: application/json
  contentType: application/json
  qps: 100
  burst: 130
controllers:
  plant:
    syncPeriod: 10s
    concurrentSyncs: 5
  shoot:
    concurrentSyncs: 20
    syncPeriod: 1h
    retryDuration: 24h
#    `respectSyncPeriodOverwrite` specifies whether Shoot owners can
#    mark their Shoots ignored (no reconciliation) or change their sync period.
#    respectSyncPeriodOverwrite: true
#    `reconcileInMaintenanceOnly` specifies whether Shoot reconciliations
#    can only happen during their maintenance time window or not.
#    reconcileInMaintenanceOnly: true
  shootCare:
    concurrentSyncs: 5
    syncPeriod: 30s
    conditionThresholds:
    - type: APIServerAvailable
      duration: 1m
    - type: ControlPlaneHealthy
      duration: 1m
    - type: SystemComponentsHealthy
      duration: 1m
    - type: EveryNodeReady
      duration: 5m
  shootMaintenance:
    concurrentSyncs: 5
  shootHibernation:
    concurrentSyncs: 5
  shootQuota:
    concurrentSyncs: 5
    syncPeriod: 60m
  seed:
    concurrentSyncs: 5
    syncPeriod: 1m
    reserveExcessCapacity: false
  backupInfrastructure:
    concurrentSyncs: 20
    syncPeriod: 24h
    deletionGracePeriodHours: 0
  backupBucket:
    concurrentSyncs: 20
    syncPeriod: 10m
  backupEntry:
    concurrentSyncs: 20
    syncPeriod: 10m
    deletionGracePeriodHours: 0
leaderElection:
  leaderElect: true
  leaseDuration: 15s
  renewDeadline: 10s
  retryPeriod: 2s
  resourceLock: configmaps
# `discovery` allows specifying options for the cached discovery client.
# discovery:
#   discoveryCacheDir: /tmp/cache-dir
#   httpCacheDir: /tmp/http-cache-dir
#   ttl: 10s
logLevel: info
kubernetesLogLevel: 0
server:
  http:
    bindAddress: 0.0.0.0
    port: 2718
  https:
    bindAddress: 0.0.0.0
    port: 2719
    tls:
      serverCertPath: dev/tls/gardener-controller-manager.crt
      serverKeyPath: dev/tls/gardener-controller-manager.key
shootBackup:
  schedule: "0 */24 * * *"
featureGates:
  Logging: true