---
apiVersion: garden.sapcloud.io/v1beta1
kind: CloudProfile
metadata:
  name: aws
spec:
# caBundle: |
#   -----BEGIN CERTIFICATE-----
#   ...
#   -----END CERTIFICATE-----
  aws:
    constraints:
      dnsProviders:
      - name: unmanaged
      kubernetes:
        versions:
        - 1.15.2
        - 1.14.5
        - 1.13.9
        - 1.12.10
        - 1.11.10
        - 1.10.13
      machineImages:
      - name: coreos
        versions:
        - version: 2023.5.0
        # Proper mappings to region-specific AMIs must exist in the `Worker` controller of the provider extension.
      machineTypes:
      - name: m5.large
        cpu: "2"
        gpu: "0"
        memory: 8Gi
        usable: true
      - name: m5.xlarge
        cpu: "4"
        gpu: "0"
        memory: 16Gi
        usable: true
      - name: m5.2xlarge
        cpu: "8"
        gpu: "0"
        memory: 32Gi
        usable: true
      - name: m5.4xlarge
        cpu: "16"
        gpu: "0"
        memory: 64Gi
        usable: true
      - name: m5.12xlarge
        cpu: "48"
        gpu: "0"
        memory: 192Gi
        usable: true
      - name: m5.24xlarge
        cpu: "96"
        gpu: "0"
        memory: 384Gi
        usable: false
      - name: p2.xlarge
        cpu: "4"
        gpu: "1"
        memory: 61Gi
      - name: p2.8xlarge
        cpu: "32"
        gpu: "8"
        memory: 488Gi
      - name: p2.16xlarge
        cpu: "64"
        gpu: "16"
        memory: 732Gi
      volumeTypes:
      - name: gp2
        class: standard
        usable: true
      - name: io1
        class: premium
        usable: false
      zones:
      - region: eu-west-1
        names:
        - eu-west-1a
        - eu-west-1b
        - eu-west-1c
      - region: us-east-1
        names:
        - us-east-1a
        - us-east-1b
        - us-east-1c
