---
apiVersion: garden.sapcloud.io/v1beta1
kind: CloudProfile
metadata:
  name: azure
spec:
# caBundle: |
#   -----BEGIN CERTIFICATE-----
#   ...
#   -----END CERTIFICATE-----
  azure:
    constraints:
      dnsProviders:
      - name: unmanaged
      kubernetes:
        versions:
        - 1.15.2
        - 1.14.5
        - 1.13.9
        - 1.12.10
        - 1.11.10
        - 1.10.13
      machineImages:
      - name: coreos
        versions:
        - version: 2023.5.0
        # Proper mappings to publisher, offer, and SKU names must exist in the `Worker` controller of the provider extension.
      machineTypes:
      - name: Standard_D2_v3
        cpu: "2"
        gpu: "0"
        memory: 8Gi
        usable: true
      - name: Standard_D4_v3
        cpu: "4"
        gpu: "0"
        memory: 16Gi
        usable: true
      - name: Standard_D8_v3
        cpu: "8"
        gpu: "0"
        memory: 32Gi
        usable: true
      - name: Standard_D16_v3
        cpu: "16"
        gpu: "0"
        memory: 64Gi
        usable: false
      - name: Standard_F2s
        cpu: "2"
        gpu: "0"
        memory: 4Gi
      - name: Standard_F4s
        cpu: "4"
        gpu: "0"
        memory: 8Gi
      - name: Standard_F8s
        cpu: "8"
        gpu: "0"
        memory: 16Gi
      - name: Standard_F16s
        cpu: "16"
        gpu: "0"
        memory: 32Gi
      volumeTypes:
      - name: standard
        class: standard
        usable: true
      - name: premium
        class: premium
        usable: false
    countUpdateDomains:
    - region: westeurope
      count: 5
    - region: eastus
      count: 5
    countFaultDomains:
    - region: westeurope
      count: 2
    - region: eastus
      count: 2
