---
apiVersion: garden.sapcloud.io/v1beta1
kind: CloudProfile
metadata:
  name: gcp
spec:
# caBundle: |
#   -----BEGIN CERTIFICATE-----
#   ...
#   -----END CERTIFICATE-----
  gcp:
    constraints:
      dnsProviders:
      - name: unmanaged
      kubernetes:
        versions:
        - 1.15.2
        - 1.14.5
        - 1.13.9
        - 1.12.10
        - 1.11.10
        - 1.10.13
      machineImages:
      - name: coreos
        versions:
        - version: 2023.5.0
        # Proper mappings to GCP image URLs must exist in the `Worker` controller of the provider extension.
      machineTypes:
      - name: n1-standard-2
        cpu: "2"
        gpu: "0"
        memory: 7500Mi
        usable: true
      - name: n1-standard-4
        cpu: "4"
        gpu: "0"
        memory: 15Gi
        usable: true
      - name: n1-standard-8
        cpu: "8"
        gpu: "0"
        memory: 30Gi
        usable: true
      - name: n1-standard-16
        cpu: "16"
        gpu: "0"
        memory: 60Gi
        usable: true
      - name: n1-standard-32
        cpu: "32"
        gpu: "0"
        memory: 120Gi
        usable: true
      - name: n1-standard-64
        cpu: "64"
        gpu: "0"
        memory: 240Gi
        usable: false
      volumeTypes:
      - name: pd-standard
        class: standard
        usable: true
      - name: pd-ssd
        class: premium
        usable: false
      zones:
      - region: europe-west1
        names:
        - europe-west1-b
        - europe-west1-c
        - europe-west1-d
      - region: us-east1
        names:
        - us-east1-b
        - us-east1-c
        - us-east1-d
