# Secret containing cloud provider credentials for Packet project into which the Seed cluster have been provisioned.
---
apiVersion: v1
kind: Secret
metadata:
  name: seed-packet
  namespace: garden
type: Opaque
data:
  apiToken: base64(api-token)
  kubeconfig: base64(kubeconfig-for-seed-cluster)
