# Secret containing cloud provider object store credentials for OpenStack Swift tenant into which the backup will be stored.
# The credentials provided in secret should have privileges to manipulate containers and objects within it.
---
apiVersion: v1
kind: Secret
metadata:
  name: backup-openstack
  namespace: garden
type: Opaque
data:
  domainName: base64(domain-name)
  tenantName: base64(tenant-name)
  username: base64(username)
  password: base64(password)
  authURL: base64(authURL)
