# Secret containing cloud provider object store credentials for AWS account into which the backup will be stored.
# The credentials provided in secret should have privileges to manipulate buckets and objects within it.
---
apiVersion: v1
kind: Secret
metadata:
  name: backup-aws
  namespace: garden
type: Opaque
data:
  accessKeyID: base64(access-key-id)
  secretAccessKey: base64(secret-access-key)
