# Secret containing cloud provider object store credentials for Alicloud project into which the backup will be stored.
# The credentials provided in secret should have privileges to manipulate buckets and objects within it.
---
apiVersion: v1
kind: Secret
metadata:
  name: backup-alicloud
  namespace: garden
type: Opaque
data:
  accessKeyID: base64(access-key-id)
  accessKeySecret: base64(access-key-secret)
  storageEndpoint: base64(storage-endpoint)
