# Secret containing cloud provider object store credentials for GCP project into which the backup will be stored.
# The credentials provided in secret should have privileges to manipulate buckets and objects within it.
---
apiVersion: v1
kind: Secret
metadata:
  name: backup-gcp
  namespace: garden
type: Opaque
data:
  serviceaccount.json: base64(serviceaccount-json)
