# Secret containing cloud provider object store credentials for Azure subscription into which the backup will be stored.
# The credentials provided in secret should have privileges to manipulate containers and objects within it.
---
apiVersion: v1
kind: Secret
metadata:
  name: backup-azure
  namespace: garden
type: Opaque
data:
  tenantID: base64(uuid-of-tenant)
  subscriptionID: base64(uuid-of-subscription)
  clientID: base64(uuid-of-client)
  clientSecret: base64(client-secret)
