# Secret containing cloud provider object store credentials for AWS account into which the backup will be stored.
# The credentials provided in secret should have privileges to manipulate buckets and objects within it.
---
apiVersion: v1
kind: Secret
metadata:
  name: seed-backup
  namespace: garden
type: Opaque
data:
  # Provider-related secret keys
  #
  # Please checkout the documentation and example manifests of your provider to find out which data keys
  # are expected.
