# Quota object limiting the resources consumed by shoot clusters either per provider secret or per project/namespace.
---
apiVersion: core.gardener.cloud/v1alpha1
kind: Quota
metadata:
  name: trial-quota
  namespace: garden-trial
spec:
  scope: # options are either core.gardener.cloud/v1alpha1.Project or v1.Secret
    apiVersion: core.gardener.cloud/v1alpha1
    kind: Project
# clusterLifetimeDays: 14
  metrics:
    cpu: "200"
    gpu: "20"
    memory: 4000Gi
    storage.standard: 8000Gi
    storage.premium: 2000Gi
    loadbalancer: "100"
