# Secret containing cloud provider credentials for Azure subscription into which Shoot clusters should be provisioned.
---
apiVersion: v1
kind: Secret
metadata:
  name: core-azure
  namespace: garden-dev
  labels:
    cloudprofile.garden.sapcloud.io/name: azure # label is only meaningful for Gardener dashboard
type: Opaque
data:
  tenantID: base64(uuid-of-tenant)
  subscriptionID: base64(uuid-of-subscription)
  clientID: base64(uuid-of-client)
  clientSecret: base64(client-secret)
  # If you use your own domain (not the default domain of your landscape) then you have to add additional keys to this secret.
  # The reason is that the DNS management is not part of the Gardener core code base but externalized, hence, it might use other
  # key names than Gardener itself.
  # The actual values here depend on the DNS extension that is installed to your landscape.
  # For example, check out https://github.com/gardener/external-dns-management and find a lot of example secret manifests here:
  # https://github.com/gardener/external-dns-management/tree/master/examples
