# Secret containing provider-specific credentials for account that shall be used to deploy the shoot into.
---
apiVersion: v1
kind: Secret
metadata:
  name: my-provider-account
  namespace: garden-dev
type: Opaque
data:
  # Provider-related secret keys
  #
  # Please checkout the documentation and example manifests of your provider to find out which data keys
  # are expected.
  #
  #
  # DNS-related secret keys
  #
  # If you use your own domain (not the default domain of your landscape) then you have to add additional keys to this secret.
  # The reason is that the DNS management is not part of the Gardener core code base but externalized, hence, it might use other
  # key names than Gardener itself.
  # The actual values here depend on the DNS extension that is installed to your landscape.
  # For example, check out https://github.com/gardener/external-dns-management and find a lot of example secret manifests here:
  # https://github.com/gardener/external-dns-management/tree/master/examples
