# SecretBindings bind a secret from the same or another namespace together with Quotas from the same or other namespaces.
---
apiVersion: garden.sapcloud.io/v1beta1
kind: SecretBinding
metadata:
  name: my-provider-account
  namespace: garden-dev
secretRef:
  name: my-provider-account
# namespace: namespace-other-than-'garden-dev' // optional
quotas: []
# - name: quota-1
# # namespace: namespace-other-than-'garden-dev' // optional
