apiVersion: {{ include "deploymentversion" . }}
kind: Deployment
metadata:
  name: kube-addon-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app: kubernetes
    role: addon-manager
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: kubernetes
      role: addon-manager
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        checksum/configmap-admission-controls: {{ include (print $.Template.BasePath "/admission-controls.yaml") . | sha256sum }}
        checksum/secret-core-addons: {{ include (print $.Template.BasePath "/core-addons.yaml") . | sha256sum }}
        checksum/secret-optional-addons: {{ include (print $.Template.BasePath "/optional-addons.yaml") . | sha256sum }}
{{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
      labels:
        app: kubernetes
        role: addon-manager
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: kube-addon-manager
        image: {{ index .Values.images "kube-addon-manager" }}
        imagePullPolicy: IfNotPresent
        env:
        - name: ADDON_MANAGER_LEADER_ELECTION
          value: "false"
        - name: KUBECTL_OPTS
          value: "--kubeconfig=/var/lib/kube-addon-manager/kubeconfig"
        - name: KUBECTL_EXTRA_PRUNE_WHITELIST
          value: "admissionregistration.k8s.io/v1alpha1/InitializerConfiguration admissionregistration.k8s.io/v1beta1/MutatingWebhookConfiguration admissionregistration.k8s.io/v1beta1/ValidatingWebhookConfiguration apiregistration.k8s.io/v1/APIService autoscaling/v1/HorizontalPodAutoscaler core/v1/LimitRange core/v1/ResourceQuota core/v1/ServiceAccount extensions/v1beta1/Ingress extensions/v1beta1/PodSecurityPolicy networking.k8s.io/v1/NetworkPolicy policy/v1beta1/PodDisruptionBudget rbac.authorization.k8s.io/v1/ClusterRole rbac.authorization.k8s.io/v1/ClusterRoleBinding rbac.authorization.k8s.io/v1/Role rbac.authorization.k8s.io/v1/RoleBinding storage.k8s.io/v1/StorageClass"
          # addon-manager executes kubectl apply -f /etc/kubernetes/addons/, but because there are hidden ../data files,
          # it applies every single file 2 times.
        - name: ADDON_PATH
          value: "/etc/kubernetes/addons/cloud-config/..data/.,/etc/kubernetes/addons/core/..data/.{{ if .Values.optionalAddonsContent }},/etc/kubernetes/addons/optional/..data/.{{ end }}"
        resources:
          requests:
            cpu: 100m
            memory: 30Mi
          limits:
            cpu: 300m
            memory: 128Mi
        volumeMounts:
        - mountPath: /etc/kubernetes/addons/cloud-config
          name: cloud-config
          readOnly: true
        - mountPath: /etc/kubernetes/addons/core
          name: core-addons
          readOnly: true
        - mountPath: /etc/kubernetes/addons/optional
          name: optional-addons
          readOnly: true
        - mountPath: /etc/kubernetes/admission-controls
          name: admission-controls
          readOnly: true
        - mountPath: /var/lib/kube-addon-manager
          name: kube-addon-manager
          readOnly: true
      volumes:
      - name: kube-addon-manager
        secret:
          secretName: kube-addon-manager
      - name: admission-controls
        configMap:
          name: kube-addon-manager-admission-controls
      - name: cloud-config
        secret:
          secretName: kube-addon-manager-cloud-config
      - name: core-addons
        secret:
          secretName: kube-addon-manager-core-addons
      - name: optional-addons
        secret:
          secretName: kube-addon-manager-optional-addons
