apiVersion: v1
kind: Service
metadata:
  name: kube-apiserver
  namespace: {{ .Release.Namespace }}
  labels:
    app: kubernetes
    role: apiserver
spec:
  type: {{ .Values.type }}
  selector:
    app: kubernetes
    role: apiserver
  ports:
  - name: kube-apiserver
    protocol: TCP
    port: 443
    targetPort: {{ .Values.targetPort }}
{{- if .Values.nodePort }}
    nodePort: {{ .Values.nodePort }}
{{- end }}
