groups:
- name: alertmanager.rules
  rules:
  - alert: AlertmanagerConfigInconsistent
    expr: count_values("config_hash", alertmanager_config_hash) / kube_statefulset_replicas{namespace="kube-system",statefulset="alertmanager"} != 1
    for: 5m
    labels:
      service: alertmanager
      severity: warning
      type: seed
    annotations:
      summary: Alertmanager configurations are inconsistent
      description: The configuration of the instances of the Alertmanager are out of sync.
  - alert: AlertmanagerFailedReload
    expr:  alertmanager_config_last_reload_successful == 0
    for: 10m
    labels:
      service: alertmanager
      severity: warning
      type: seed
    annotations:
      summary: Alertmanager configuration reload has failed
      description: Reloading Alertmanager's configuration has failed for {{ $labels.pod}}.
