groups:
- name: vpn.rules
  rules:
  - alert: VPNShootNoPods
    expr: kube_deployment_status_replicas_available{deployment="vpn-shoot"} == 0
    for: 5m
    labels:
      service: vpn
      severity: critical
      type: shoot
    annotations:
      description: vpn-shoot deployment in Shoot cluster has 0 available pods. VPN won't work.
      summary: VPN Shoot deployment no pods
  - alert: VPNConnectionDown
    expr: absent(probe_success{job="vpn-connection"}) == 1 or probe_success{job="vpn-connection"} != 1
    for: 5m
    labels:
      service: vpn
      severity: critical
      type: shoot
    annotations:
      description: VPN connection check failed. No communication from control plane (Prometheus pod) to the Shoot workers possible.
      summary: VPN connection down
  - alert: VPNProbeAPIServerProxyFailed
    expr: absent(probe_success{job="vpn-probe-apiserver-proxy"}) == 1 or probe_success{job="vpn-probe-apiserver-proxy"} == 0 or probe_http_status_code{job="vpn-probe-apiserver-proxy"} != 200
    for: 10m
    labels:
      service: vpn
      severity: critical
      type: shoot
    annotations:
      description: The API Server proxy functionality is not working. Probably the vpn connection from an API Server pod to the vpn-shoot endpoint on the Shoot workers does not work.
      summary: API Server Proxy not usable
  - alert: VPNProbeK8sServiceFailed
    expr: absent(probe_success{job="vpn-probe-apiserver-proxy"}) == 1 or probe_success{job="vpn-probe-apiserver-proxy"} != 1
    for: 10m
    labels:
      service: vpn
      severity: warning
      type: shoot
    annotations:
      description: The VPN probe via the kubernetes service does not work. The vpn connection from Prometheus to the vpn-shoot endpoint on the Shoot workers or the communication from the Shoot workers to the API Server via the kubernetes service is not working.
      summary: VPN probe via kubernetes service failed
