podAnnotations: {}
replicas: 1

images:
  cluster-autoscaler: image-repository:image-tag

namespace:
  uid: uuid-of-namespace

workerPools:
- name: foo
  min: 1
  max: 3

metricsPort: 8085

scaleDownUnneededTime: 30m0s
scaleDownDelayAfterAdd: 1h0m0s
# scaleDownUtilizationThreshold: foo
# scaleDownDelayAfterFailure: foo
# scaleDownDelayAfterDelete: foo
# scanInterval: foo
