apiVersion: {{ include "deploymentversion" . }}
kind: Deployment
metadata:
  name: service-check
  namespace: kube-system
  labels:
    garden.sapcloud.io/role: system-component
    component: service-check
    addonmanager.kubernetes.io/mode: Reconcile
    origin: gardener
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      component: service-check
  template:
    metadata:
      labels:
        origin: gardener
        garden.sapcloud.io/role: system-component
        component: service-check
    spec:
      containers:
      - name: blackbox-exporter
        image: {{ index .Values.images "blackbox-exporter" }}
        args:
        - --config.file=/etc/blackbox_exporter/blackbox.yaml
        imagePullPolicy: IfNotPresent
        # TODO: network rootnamespace
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 75m
            memory: 75Mi
        ports:
        - containerPort: 9115
          protocol: TCP
          name: probe
        volumeMounts:
        - name: blackbox-exporter-config
          mountPath: /etc/blackbox_exporter
      volumes:
      - name: blackbox-exporter-config
        configMap:
          name: blackbox-exporter-config
---
apiVersion: v1
kind: Service
metadata:
  name: service-check
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    component: service-check
spec:
  type: ClusterIP
  ports:
  - name: probe
    port: 9115
    protocol: TCP
  selector:
    component: service-check
