---
apiVersion: v1
kind: Secret
metadata:
  name: extensions-dns-{{ .Values.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{ toYaml .Values.secretData | indent 2 }}
---
apiVersion: dns.gardener.cloud/v1alpha1
kind: DNSProvider
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
{{- if ne .Values.purpose "internal" }}
  annotations:
    dns.gardener.cloud/realms: "{{ .Release.Namespace }},"
{{- end }}
spec:
  type: {{ .Values.provider }}
  secretRef:
    name: extensions-dns-{{ .Values.name }}
{{- if or .Values.domains.include .Values.domains.exclude }}
{{- if .Values.domains.include }}
  domains:
    include:
{{ toYaml .Values.domains.include | indent 4 }}
{{- end }}
{{- if .Values.domains.exclude }}
    exclude:
{{ toYaml .Values.domains.exclude | indent 4 }}
{{- end }}
{{- end }}
{{- if or .Values.zones.include .Values.zones.exclude }}
  zones:
{{- if .Values.zones.include }}
    include:
{{ toYaml .Values.zones.include | indent 4 }}
{{- end }}
{{- if .Values.zones.exclude }}
    exclude:
{{ toYaml .Values.zones.exclude | indent 4 }}
{{- end }}
{{- end }}
