osc:
  type: coreos
  purpose: bootstrap
  reloadConfigFilePath: /var/lib/...
  secretName: cpu-worker-0

#caBundle: |
#  root certificates
images:
  hyperkube: image-repository
  pause-container: image-repository
kubernetes:
  clusterDNS: 100.64.0.10
  domain: cluster.local
  version: 1.11.2
worker:
  name: cpu-worker
  kubelet:
    caCert: abcd
    cpuCFSQuota: true
    cpuManagerPolicy: none
#    podPIDsLimit: 24
    maxPods: 110
    evictionPressureTransitionPeriod: 4m0s
    evictionMaxPodGracePeriod: 90
    evictionHard:
      memoryAvailable: 100Mi
      imageFSAvailable: 5%
      imageFSInodesFree: 5%
      nodeFSAvailable: 5%
      nodeFSInodesFree: 5%
    evictionSoft:
      memoryAvailable: 200Mi
      imageFSAvailable: 10%
      imageFSInodesFree: 10%
      nodeFSAvailable: 10%
      nodeFSInodesFree: 10%
    evictionSoftGracePeriod:
      memoryAvailable: 1m30s
      imageFSAvailable: 1m30s
      imageFSInodesFree: 1m30s
      nodeFSAvailable: 1m30s
      nodeFSInodesFree: 1m30s
    evictionMinimumReclaim:
      memoryAvailable: 0Mi
      imageFSAvailable: 0Mi
      imageFSInodesFree: 0Mi
      nodeFSAvailable: 0Mi
      nodeFSInodesFree: 0Mi

    featureGates: {}
  #     CustomResourceValidation: true
  #     RotateKubeletServerCertificate: false

