groups:
- name: coredns.rules
  rules:
  - alert: CoreDNSDown
    expr: absent(up{job="coredns"} == 1)
    for: 20m
    labels:
      service: kube-dns
      severity: critical
      type: shoot
      visibility: all
    annotations:
      description: CoreDNS could not be found. Cluster DNS resolution will not work.
      summary: CoreDNS is down