groups:
- name: kube-state-metrics.rules
  rules:
  - alert: KubeStateMetricsShootDown
    expr: absent(up{job="kube-state-metrics", type="shoot"} == 1)
    for: 5m
    labels:
      service: kube-state-metrics-shoot
      severity: info
      visibility: operator
      type: seed
    annotations:
      summary: Kube-state-metrics for shoot cluster metrics is down.
      description: There are no running kube-state-metric pods for the shoot cluster. No kubernetes resource metrics can be scraped.

  - alert: KubeStateMetricsSeedDown
    expr: absent(up{job="kube-state-metrics", type="seed"} == 1)
    for: 5m
    labels:
      service: kube-state-metrics-seed
      severity: critical
      visibility: operator
      type: seed
    annotations:
      summary: Kube-state-metrics for seed cluster metrics is down.
      description: There are no running kube-state-metric pods for the seed cluster. No kubernetes resource metrics can be scraped.

  - alert: NoWorkerNodes
    expr: sum(kube_node_spec_unschedulable) == count(kube_node_info) or absent(kube_node_info)
    for: 25m # MCM timeout + grace period to allow self healing before firing alert
    labels:
      service: nodes
      severity: blocker
      visibility: all
    annotations:
      description: There are no worker nodes in the cluster or all of the worker nodes in the cluster are not schedulable.
      summary: No nodes available. Possibly all workloads down.