groups:
- name: kube-etcd3.rules
  rules:
  # alert if main etcd is down
  - alert: KubeEtcdMainDown
    expr: sum(up{job="kube-etcd3",role="main"}) < 1
    for: 5m
    labels:
      service: etcd
      severity: blocker
      type: seed
      visibility: operator
    annotations:
      description: Etcd3 cluster main is unavailable or cannot be scraped. As long as etcd3 main is down the cluster is unreachable.
      summary: Etcd3 main cluster down.
  # alert if events etcd is down
  - alert: KubeEtcdEventsDown
    expr: sum(up{job="kube-etcd3",role="events"}) < 1
    for: 15m
    labels:
      service: etcd
      severity: critical
      type: seed
      visibility: operator
    annotations:
      description: Etcd3 cluster events is unavailable or cannot be scraped. Cluster events cannot be collected.
      summary: Etcd3 events cluster down.
  # etcd leader alerts
  - alert: KubeEtcd3MainNoLeader
    expr: sum(etcd_server_has_leader{job="kube-etcd3",role="main"}) < count(etcd_server_has_leader{job="kube-etcd3",role="main"})
    for: 10m
    labels:
      service: etcd
      severity: critical
      type: seed
      visibility: operator
    annotations:
      description: Etcd3 main has no leader. No communication with etcd main possible. Apiserver is read only.
      summary: Etcd3 main has no leader.
  - alert: KubeEtcd3EventsNoLeader
    expr: sum(etcd_server_has_leader{job="kube-etcd3",role="events"}) < count(etcd_server_has_leader{job="kube-etcd3",role="events"})
    for: 15m
    labels:
      service: etcd
      severity: critical
      type: seed
      visibility: operator
    annotations:
      description: Etcd3 events has no leader. No communication with etcd events possible. New cluster events cannot be collected. Events can only be read.
      summary: Etcd3 events has no leader.

  ### etcd proposal alerts ###
  # alert if there are several failed proposals within an hour
  # Note: Increasing the failedProposals count to 80, known issue in etcd, fix in progress
  # https://github.com/kubernetes/kubernetes/pull/64539 - fix in Kubernetes to be released with v1.15
  # https://github.com/etcd-io/etcd/issues/9360 - ongoing discussion in etcd
  - alert: KubeEtcd3HighNumberOfFailedProposals
    expr: increase(etcd_server_proposals_failed_total{job="kube-etcd3"}[1h]) > 80
    labels:
      service: etcd
      severity: warning
      type: seed
      visibility: operator
    annotations:
      description: Etcd3 pod {{ $labels.pod }} has seen {{ $value }} proposal failures
        within the last hour.
      summary: High number of failed etcd proposals
  
  - record: shoot:etcd_object_counts:sum_by_resource
    expr: sum(etcd_object_counts) by (resource)
  
  # etcd backup failure alerts
  - alert: KubeEtcdDeltaBackupFailed
    expr: changes(etcdbr_snapshot_latest_revision{job="kube-etcd3-backup-restore",role="main",kind="Incr"}[15m]) >= 1 and ON(job,role,kind) changes(etcdbr_snapshot_duration_seconds_count{job="kube-etcd3-backup-restore",role="main",kind="Incr",succeeded="true"}[15m]) < 1
    labels:
      service: etcd
      severity: critical
      type: seed
      visibility: operator
    annotations:
      description: No delta snapshot for the past 15 minutes.
      summary: Etcd delta snapshot failure.
  - alert: KubeEtcdFullBackupFailed
    expr: changes(etcdbr_snapshot_latest_revision{job="kube-etcd3-backup-restore",role="main",kind="Full"}[1455m]) >= 1 and ON(job,role,kind) changes(etcdbr_snapshot_duration_seconds_count{job="kube-etcd3-backup-restore",role="main",kind="Full",succeeded="true"}[1455m]) < 1
    labels:
        service: etcd
        severity: critical
        type: seed
        visibility: operator
    annotations:
        description: No full snapshot for the past 24 hours 15minutes.
        summary: Etcd full snapshot failure.

  