{{- if .Values.controller.certificateManagement }}
---
apiVersion: v1
kind: Secret
metadata:
  name: certificate-management
  namespace: garden
  labels:
    garden.sapcloud.io/role: certificate-management
type: Opaque
data:
  certificate-management-config: {{ .Values.controller.certificateManagement | b64enc }}
{{- end }}