apiVersion: "autoscaling.k8s.io/v1beta2"
kind: VerticalPodAutoscaler
metadata:
  name: etcd-{{ .Values.role }}-vpa
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    apiVersion: {{ include "statefulsetversion" . }}
    kind: StatefulSet
    name: etcd-{{ .Values.role }}
  updatePolicy:
    updateMode: "Off"