apiVersion: v1
kind: Service
metadata:
  name: etcd-{{ .Values.role }}-client
  namespace: {{ .Release.Namespace }}
  labels:
    app: etcd-statefulset
    role: {{ .Values.role }}
spec:
  type: ClusterIP
  sessionAffinity: None
  selector:
    app: etcd-statefulset
    role: {{ .Values.role }}
  ports:
  - name: client
    protocol: TCP
    port: {{ .Values.servicePorts.client }}
    targetPort: {{ .Values.servicePorts.client }}
  - name: server
    protocol: TCP
    port: {{ .Values.servicePorts.server }}
    targetPort: {{ .Values.servicePorts.server }}
  - name: backuprestore
    protocol: TCP
    port: {{ .Values.servicePorts.backuprestore }}
    targetPort: {{ .Values.servicePorts.backuprestore }}