---
apiVersion: {{ include "initializeradmissionregistrationversion" . }}
kind: InitializerConfiguration
metadata:
  name: pvlabel.kubernetes.io
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
initializers:
- name: pvlabel.kubernetes.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - "*"
    resources:
    - persistentvolumes
