---
apiVersion: {{ include "rbacversion" . }}
kind: ClusterRoleBinding
metadata:
  name: garden.sapcloud.io:system:project:{{ .Values.project.name }}
  ownerReferences:
  - apiVersion: garden.sapcloud.io/v1beta1
    kind: Project
    blockOwnerDeletion: false
    controller: true
    name: {{ .Values.project.name }}
    uid: {{ .Values.project.uid }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: garden.sapcloud.io:system:project:{{ .Values.project.name }}
subjects:
{{ toYaml .Values.project.owners }}
