apiVersion: {{ include "ingressversion" . }}
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required
    nginx.ingress.kubernetes.io/auth-secret: grafana-{{ .Values.role }}-basic-auth
    nginx.ingress.kubernetes.io/auth-type: basic
  name: grafana-{{ .Values.role }}
  namespace: {{ .Release.Namespace }}
  labels:
    component: grafana
    role: {{ .Values.role }}
spec:
  tls:
  - secretName: grafana-{{ .Values.role }}-tls
    hosts:
    - {{ .Values.ingress.host }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          servicePort: {{ required ".ports.grafana is required" .Values.ports.grafana }}
          serviceName: grafana-{{ .Values.role }}
        path: /
