{{ if .Values.vpa.enabled }}
apiVersion: "autoscaling.k8s.io/v1beta2"
kind: VerticalPodAutoscaler
metadata:
  name: prometheus-vpa
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    apiVersion: {{ include "statefulsetversion" . }}
    kind: StatefulSet
    name: prometheus
  updatePolicy:
    updateMode: "Off"
{{ end }}