apiVersion: {{ include "networkpolicyversion" . }}
kind: NetworkPolicy
metadata:
  annotations:
    gardener.cloud/description: |
      Allows Egress from pods labeled with 'networking.gardener.cloud/to-shoot-networks=allowed'
      to IPv4 blocks belonging to the Shoot network.

      In practice, this should be used by components which use 'vpn-seed' to communicate to Pods
      in the Shoot cluster.
  name: allow-to-shoot-networks
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      networking.gardener.cloud/to-shoot-networks: allowed
  egress:
  - to:
{{ template "global-network-policies.except-networks" .Values.clusterNetworks }}
  policyTypes:
  - Egress
  ingress: []
