---
apiVersion: {{ include "deploymentversion" . }}
kind: Deployment
metadata:
  name: vpn-shoot
  namespace: kube-system
  labels:
    garden.sapcloud.io/role: system-component
    app: vpn-shoot
    addonmanager.kubernetes.io/mode: Reconcile
    origin: gardener
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: vpn-shoot
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        checksum/secret-vpn-shoot-dh: {{ include (print $.Template.BasePath "/secret-dh.yaml") . | sha256sum }}
        checksum/secret-vpn-shoot-tlsauth: {{ include (print $.Template.BasePath "/secret-tlsauth.yaml") . | sha256sum }}
{{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
      labels:
        origin: gardener
        garden.sapcloud.io/role: system-component
        app: vpn-shoot
    spec:
      automountServiceAccountToken: false
      serviceAccountName: vpn-shoot
      priorityClassName: system-cluster-critical
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
{{- if .Values.initContainers }}
      initContainers:
      {{- range $index, $ctr := .Values.initContainers }}
      - name: init-{{ $index }}
        image: {{ $ctr.image }}
        {{- if $ctr.command }}
        command:
{{ toYaml $ctr.command | indent 8 }}
        {{- end }}
        volumeMounts:
        - name: shared-init-config
          mountPath: /init-config
      {{- end }}
{{- end }}
      containers:
      - name: vpn-shoot
        image: {{ index .Values.images "vpn-shoot" }}
        imagePullPolicy: IfNotPresent
        env:
        - name: SERVICE_NETWORK
          value: {{ .Values.serviceNetwork }}
        - name: POD_NETWORK
          value: {{ .Values.podNetwork }}
        - name: NODE_NETWORK
          value: {{ .Values.nodeNetwork }}
        securityContext:
          privileged: true
          capabilities:
            add:
            - NET_ADMIN
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - mountPath: /srv/secrets/vpn-shoot
          name: vpn-shoot
        - mountPath: /srv/secrets/tlsauth
          name: vpn-shoot-tlsauth
        - mountPath: /srv/secrets/dh
          name: vpn-shoot-dh
        - name: shared-init-config
          mountPath: /init-config
      volumes:
      - name: vpn-shoot
        secret:
          secretName: vpn-shoot
      - name: vpn-shoot-tlsauth
        secret:
          secretName: vpn-shoot-tlsauth
      - name: vpn-shoot-dh
        secret:
          secretName: vpn-shoot-dh
      - name: shared-init-config
        emptyDir: {}
