apiVersion: v1
kind: ServiceAccount
metadata:
  name: gardener-resource-manager
  namespace: {{ .Release.Namespace }}
  labels:
    garden.sapcloud.io/role: controlplane
    app: gardener-resource-manager
