{{- if .Values.global.apiserver.enabled }}
apiVersion: {{ include "deploymentversion" . }}
kind: Deployment
metadata:
  name: gardener-apiserver
  namespace: garden
  labels:
    app: gardener
    role: apiserver
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ required ".Values.global.apiserver.replicaCount is required" .Values.global.apiserver.replicaCount }}
  selector:
    matchLabels:
      app: gardener
      role: apiserver
  template:
    metadata:
      annotations:
        {{- if .Values.global.apiserver.audit.policy }}
        checksum/configmap-gardener-audit-policy-config: {{ include (print $.Template.BasePath "/configmap-apiserver-audit-policy.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.global.apiserver.audit.webhook.config }}
        checksum/secret-gardener-audit-webhook-config: {{ include (print $.Template.BasePath "/secret-apiserver-audit-webhook-config.yaml") . | sha256sum }}
        {{- end }}
        checksum/secret-gardener-apiserver-cert: {{ include (print $.Template.BasePath "/secret-apiserver-cert.yaml") . | sha256sum }}
        checksum/secret-gardener-apiserver-kubeconfig: {{ include (print $.Template.BasePath "/secret-apiserver-kubeconfig.yaml") . | sha256sum }}
      labels:
        app: gardener
        role: apiserver
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
        {{- if .Values.global.apiserver.etcd.useSidecar }}
        sidecar: etcd
        {{- end }}
    spec:
      {{- if not .Values.global.apiserver.kubeconfig }}
      serviceAccountName: {{ required ".Values.global.apiserver.serviceAccountName is required" .Values.global.apiserver.serviceAccountName }}
      {{- end }}
      containers:
      - name: gardener-apiserver
        image: {{ required ".Values.global.apiserver.image.repository is required" .Values.global.apiserver.image.repository }}:{{ required ".Values.global.apiserver.image.tag is required" .Values.global.apiserver.image.tag }}
        imagePullPolicy: {{ .Values.global.apiserver.image.pullPolicy }}
        command:
        - /gardener-apiserver
        {{- if .Values.global.apiserver.audit.dynamicConfiguration }}
        - --audit-dynamic-configuration={{ .Values.global.apiserver.audit.dynamicConfiguration }}
        {{- end }}
        {{- if .Values.global.apiserver.audit.log.batchBufferSize }}
        - --audit-log-batch-buffer-size={{ .Values.global.apiserver.audit.log.batchBufferSize }}
        {{- end }}
        {{- if .Values.global.apiserver.audit.log.batchMaxSize }}
        - --audit-log-batch-max-size={{ .Values.global.apiserver.audit.log.batchMaxSize }}
        {{- end }}
        {{- if .Values.global.apiserver.audit.log.batchMaxWait }}
        - --audit-log-batch-max-wait={{ .Values.global.apiserver.audit.log.batchMaxWait }}
        {{- end }}
        {{- if .Values.global.apiserver.audit.log.batchThrottleBurst }}
        - --audit-log-batch-throttle-burst={{ .Values.global.apiserver.audit.log.batchThrottleBurst }}
        {{- end }}
        {{- if .Values.global.apiserver.audit.log.batchThrottleEnable }}
        - --audit-log-batch-throttle-enable={{ .Values.global.apiserver.audit.log.batchThrottleEnable }}
        {{- end }}
        {{- if .Values.global.apiserver.audit.log.batchThrottleQPS }}
        - --audit-log-batch-throttle-qps={{ .Values.global.apiserver.audit.log.batchThrottleQPS }}
        {{- end }}
        {{- if .Values.global.apiserver.audit.log.format }}
        - --audit-log-format={{ .Values.global.apiserver.audit.log.format }}
        {{- end }}
        {{- if .Values.global.apiserver.audit.log.maxAge }}
        - --audit-log-maxage={{ .Values.global.apiserver.audit.log.maxAge }}
        {{- end }}
        {{- if .Values.global.apiserver.audit.log.maxBackup }}
        - --audit-log-maxbackup={{ .Values.global.apiserver.audit.log.maxBackup }}
        {{- end }}
        {{- if .Values.global.apiserver.audit.log.maxSize }}
        - --audit-log-maxsize={{ .Values.global.apiserver.audit.log.maxSize }}
        {{- end }}
        {{- if .Values.global.apiserver.audit.log.mode }}
        - --audit-log-mode={{ .Values.global.apiserver.audit.log.mode }}
        {{- end }}
        {{- if .Values.global.apiserver.audit.log.path }}
        - --audit-log-path={{ .Values.global.apiserver.audit.log.path }}
        {{- end }}
        {{- if .Values.global.apiserver.audit.log.truncateEnabled }}
        - --audit-log-truncate-enabled={{ .Values.global.apiserver.audit.log.truncateEnabled }}
        {{- end }}
        {{- if .Values.global.apiserver.audit.log.truncateMaxBatchSize }}
        - --audit-log-truncate-max-batch-size={{ .Values.global.apiserver.audit.log.truncateMaxBatchSize }}
        {{- end }}
        {{- if .Values.global.apiserver.audit.log.truncateMaxEventSize }}
        - --audit-log-truncate-max-event-size={{ .Values.global.apiserver.audit.log.truncateMaxEventSize }}
        {{- end }}
        {{- if .Values.global.apiserver.audit.log.version }}
        - --audit-log-version={{ .Values.global.apiserver.audit.log.version }}
        {{- end }}
        {{- if .Values.global.apiserver.audit.policy }}
        - --audit-policy-file=/etc/gardener-apiserver/audit/audit-policy.yaml
        {{- end }}
        {{- if .Values.global.apiserver.audit.webhook.batchBufferSize }}
        - --audit-webhook-batch-buffer-size={{ .Values.global.apiserver.audit.webhook.batchBufferSize }}
        {{- end }}
        {{- if .Values.global.apiserver.audit.webhook.batchMaxSize }}
        - --audit-webhook-batch-max-size={{ .Values.global.apiserver.audit.webhook.batchMaxSize }}
        {{- end }}
        {{- if .Values.global.apiserver.audit.webhook.batchMaxWait }}
        - --audit-webhook-batch-max-wait={{ .Values.global.apiserver.audit.webhook.batchMaxWait }}
        {{- end }}
        {{- if .Values.global.apiserver.audit.webhook.batchThrottleBurst }}
        - --audit-webhook-batch-throttle-burst={{ .Values.global.apiserver.audit.webhook.batchThrottleBurst }}
        {{- end }}
        {{- if .Values.global.apiserver.audit.webhook.batchThrottleEnable }}
        - --audit-webhook-batch-throttle-enable={{ .Values.global.apiserver.audit.webhook.batchThrottleEnable }}
        {{- end }}
        {{- if .Values.global.apiserver.audit.webhook.batchThrottleQPS }}
        - --audit-webhook-batch-throttle-qps={{ .Values.global.apiserver.audit.webhook.batchThrottleQPS }}
        {{- end }}
        {{- if .Values.global.apiserver.audit.webhook.config }}
        - --audit-webhook-config-file=/etc/gardener-apiserver/auditwebhook/audit-webhook-config.yaml
        {{- end }}
        {{- if .Values.global.apiserver.audit.webhook.initialBackoff }}
        - --audit-webhook-initial-backoff={{ .Values.global.apiserver.audit.webhook.initialBackoff }}
        {{- end }}
        {{- if .Values.global.apiserver.audit.webhook.mode }}
        - --audit-webhook-mode={{ .Values.global.apiserver.audit.webhook.mode }}
        {{- end }}
        {{- if .Values.global.apiserver.audit.webhook.truncateEnabled }}
        - --audit-webhook-truncate-enabled={{ .Values.global.apiserver.audit.webhook.truncateEnabled }}
        {{- end }}
        {{- if .Values.global.apiserver.audit.webhook.truncateMaxBatchSize }}
        - --audit-webhook-truncate-max-batch-size={{ .Values.global.apiserver.audit.webhook.truncateMaxBatchSize }}
        {{- end }}
        {{- if .Values.global.apiserver.audit.webhook.truncateMaxEventSize }}
        - --audit-webhook-truncate-max-event-size={{ .Values.global.apiserver.audit.webhook.truncateMaxEventSize }}
        {{- end }}
        {{- if .Values.global.apiserver.audit.webhook.version }}
        - --audit-webhook-version={{ .Values.global.apiserver.audit.webhook.version }}
        {{- end }}
        - --authorization-always-allow-paths=/healthz
        {{- if .Values.global.apiserver.etcd.useSidecar }}
        - --etcd-servers=http://localhost:2379
        {{- else }}
        - --etcd-servers={{ required ".Values.global.apiserver.etcd.servers is required" .Values.global.apiserver.etcd.servers }}
        {{- if .Values.global.apiserver.etcd.caBundle }}
        - --etcd-cafile=/etc/gardener-apiserver/srv/etcd-client-ca.crt
        {{- end }}
        {{- if .Values.global.apiserver.etcd.tls }}
        - --etcd-certfile=/etc/gardener-apiserver/srv/etcd-client.crt
        {{- end }}
        {{- if .Values.global.apiserver.etcd.tls }}
        - --etcd-keyfile=/etc/gardener-apiserver/srv/etcd-client.key
        {{- end }}
        {{- end }}
        {{- include "gardener-apiserver.featureGates" . | trimSuffix "," | indent 8 }}
        {{- if .Values.global.apiserver.kubeconfig }}
        - --authentication-kubeconfig=/etc/gardener-apiserver/kubeconfig/kubeconfig
        - --authorization-kubeconfig=/etc/gardener-apiserver/kubeconfig/kubeconfig
        - --kubeconfig=/etc/gardener-apiserver/kubeconfig/kubeconfig
        {{- end }}
        - --secure-port=443
        - --tls-cert-file=/etc/gardener-apiserver/srv/gardener-apiserver.crt
        - --tls-private-key-file=/etc/gardener-apiserver/srv/gardener-apiserver.key
        - --v=2
        {{- if .Values.global.apiserver.resources }}
        resources:
{{ toYaml .Values.global.apiserver.resources | indent 10 }}
        {{- end }}
        {{- if .Values.global.apiserver.dnsConfig }}
        dnsConfig:
{{ toYaml .Values.global.apiserver.dnsConfig | indent 10 }}
        {{- end }}
        volumeMounts:
        - name: gardener-apiserver-cert
          mountPath: /etc/gardener-apiserver/srv
          readOnly: true
        {{- if .Values.global.apiserver.kubeconfig }}
        - name: gardener-apiserver-kubeconfig
          mountPath: /etc/gardener-apiserver/kubeconfig
          readOnly: true
        {{- end }}
        {{- if .Values.global.apiserver.audit.policy }}
        - name: gardener-audit-policy-config
          mountPath: /etc/gardener-apiserver/audit
        {{- end }}
        {{- if .Values.global.apiserver.audit.webhook.config }}
        - name: gardener-audit-webhook-config
          mountPath: /etc/gardener-apiserver/auditwebhook
        {{- end }}
      {{- if .Values.global.apiserver.etcd.useSidecar }}
      - name: etcd
        image: quay.io/coreos/etcd:v3.3.12
        imagePullPolicy: IfNotPresent
        command:
        - /usr/local/bin/etcd
        - --data-dir=/var/etcd/data
        - --name=etcd
        - --advertise-client-urls=http://etcd:2379
        - --listen-peer-urls=http://0.0.0.0:2380
        - --listen-client-urls=http://0.0.0.0:2379
        - --initial-advertise-peer-urls=http://etcd:2380
        - --initial-cluster=etcd=http://etcd:2380
        - --initial-cluster-state=new
        - --initial-cluster-token=new
        livenessProbe:
          httpGet:
            port: 2379
            path: /health
          initialDelaySeconds: 15
          timeoutSeconds: 15
        ports:
        - name: serverport
          containerPort: 2380
        - name: clientport
          containerPort: 2379
        resources:
          requests:
            cpu: 200m
        volumeMounts:
        - name: etcd
          mountPath: /var/etcd/data
      {{- end }}
      volumes:
      {{- if .Values.global.apiserver.etcd.useSidecar }}
      - name: etcd
        emptyDir: {}
      {{- end }}
      - name: gardener-apiserver-cert
        secret:
          secretName: gardener-apiserver-cert
      {{- if .Values.global.apiserver.kubeconfig }}
      - name: gardener-apiserver-kubeconfig
        secret:
          secretName: gardener-apiserver-kubeconfig
      {{- end }}
      {{- if .Values.global.apiserver.audit.policy }}
      - name: gardener-audit-policy-config
        configMap:
          name: gardener-audit-policy-config
      {{- end }}
      {{- if .Values.global.apiserver.audit.webhook.config }}
      - name: gardener-audit-webhook-config
        secret:
          secretName: gardener-audit-webhook-config
      {{- end }}
{{- if .Values.global.apiserver.etcd.useSidecar }}
---
apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: garden
  labels:
    sidecar: etcd
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: ClusterIP
  sessionAffinity: None
  selector:
    sidecar: etcd
  ports:
  - name: discovery
    protocol: TCP
    port: 2380
    targetPort: 2380
  - name: client
    protocol: TCP
    port: 2379
    targetPort: 2379
{{- end }}
{{- end }}
