networks:
  pods: 100.96.0.0/11
  services: 100.64.0.0/13
  nodes: 10.250.0.0/16
# global:
#   shootKubeVersion:
#     gitVersion: v1.6.4

images:
  prometheus: image-repository:image-tag
  vpn-seed: image-repository:image-tag
  blackbox-exporter: image-repository:image-tag

ingress:
  host: p.seed-1.example.com
  # admin : admin base64 encoded
  basicAuthSecret: YWRtaW46JGFwcjEkSWRSaVM5c3MkR3U1MHMxaGUwL2Z6Tzh2elE4S1BEMQ==

kubernetesVersion: 1.13.1

namespace:
  uid: 100c3bb5-48b9-4f88-96ef-48ed557d4212

podAnnotations: {}
replicas: 1
apiserverServiceIP: 100.10.10.10
port: 9090
vpnEndpointIP: 192.168.123.1

allowedMetrics:
  alertManager:
  - alertmanager_config_hash
  - alertmanager_config_last_reload_successful
  - process_max_fds
  - process_open_fds
  cAdvisor:
  - container_cpu_cfs_periods_total
  - container_cpu_usage_seconds_total
  - container_fs_inodes_total
  - container_fs_limit_bytes
  - container_fs_usage_bytes
  - container_last_seen
  - container_memory_working_set_bytes
  - container_network_receive_bytes_total
  - container_network_transmit_bytes_total
  coredns:
  - process_max_fds
  - process_open_fds
  - coredns_dns_request_count_total
  - coredns_dns_request_type_count_total
  - coredns_cache_hits_total
  - coredns_cache_misses_total
  - coredns_cache_size
  - coredns_dns_response_rcode_count_total
  - coredns_forward_request_count_total
  - coredns_forward_response_rcode_count_total
  cloudControllerManager:
  - rest_client_requests_total
  - process_max_fds
  - process_open_fds
  clusterAutoscaler:
  - process_max_fds
  - process_open_fds
  kubeAPIServer:
  - apiserver_registered_watchers
  - apiserver_request_count
  - apiserver_request_total
  - apiserver_request_latencies_bucket
  - etcd_object_counts
  - process_max_fds
  - process_open_fds
  - apiserver_audit_event_total
  - apiserver_audit_error_total
  kubeControllerManager:
  - rest_client_requests_total
  - process_max_fds
  - process_open_fds
  kubelet:
  - kubelet_pod_start_latency_microseconds
  - kubelet_running_pod_count
  - process_max_fds
  - process_open_fds
  kubeETCD3:
  - etcd_disk_backend_commit_duration_seconds_bucket
  - etcd_disk_wal_fsync_duration_seconds_bucket
  - etcd_mvcc_db_total_size_in_bytes
  - etcd_network_client_grpc_received_bytes_total
  - etcd_network_client_grpc_sent_bytes_total
  - etcd_network_peer_received_bytes_total
  - etcd_network_peer_sent_bytes_total
  - etcd_server_has_leader
  - etcd_server_leader_changes_seen_total
  - etcd_server_proposals_applied_total
  - etcd_server_proposals_committed_total
  - etcd_server_proposals_failed_total
  - etcd_server_proposals_pending
  - grpc_server_handled_total
  - grpc_server_started_total
  - grpc_server_handling_seconds_count
  - grpc_server_handling_seconds_sum
  - grpc_server_handling_seconds_bucket
  - process_max_fds
  - process_open_fds
  - process_resident_memory_bytes
  kubeETCD3BR:
  - etcdbr_snapshot_gc_total
  - etcdbr_snapshot_latest_revision
  - etcdbr_snapshot_latest_timestamp
  - etcdbr_snapshot_duration_seconds_bucket
  - etcdbr_snapshot_duration_seconds_count
  - etcdbr_snapshot_duration_seconds_sum
  - etcdbr_validation_duration_seconds_bucket
  - etcdbr_validation_duration_seconds_count
  - etcdbr_validation_duration_seconds_sum
  - etcdbr_restoration_duration_seconds_bucket
  - etcdbr_restoration_duration_seconds_count
  - etcdbr_restoration_duration_seconds_sum
  - etcdbr_defragmentation_duration_seconds_bucket
  - etcdbr_defragmentation_duration_seconds_count
  - etcdbr_defragmentation_duration_seconds_sum
  - etcdbr_network_transmitted_bytes
  - etcdbr_network_received_bytes
  - process_resident_memory_bytes
  kubeScheduler:
  - scheduler_binding_latency_microseconds_bucket
  - scheduler_e2e_scheduling_latency_microseconds_bucket
  - scheduler_scheduling_algorithm_latency_microseconds_bucket
  - rest_client_requests_total
  - process_max_fds
  - process_open_fds
  kubeStateMetrics:
  - kube_daemonset_status_current_number_scheduled
  - kube_daemonset_metadata_generation
  - kube_daemonset_status_current_number_scheduled
  - kube_daemonset_status_number_available
  - kube_daemonset_status_number_unavailable
  - kube_daemonset_updated_number_scheduled
  - kube_daemonset_status_desired_number_scheduled
  - kube_deployment_metadata_generation
  - kube_deployment_spec_replicas
  - kube_deployment_status_observed_generation
  - kube_deployment_status_replicas
  - kube_deployment_status_replicas_available
  - kube_deployment_status_replicas_unavailable
  - kube_deployment_status_replicas_updated
  - kube_node_info
  - kube_node_labels
  - kube_node_spec_unschedulable
  - kube_node_status_allocatable_cpu_cores
  - kube_node_status_allocatable_memory_bytes
  - kube_node_status_allocatable_pods
  - kube_node_status_capacity_cpu_cores
  - kube_node_status_capacity_memory_bytes
  - kube_node_status_capacity_pods
  - kube_node_status_condition
  - kube_pod_container_info
  - kube_pod_container_resource_limits_cpu_cores
  - kube_pod_container_resource_limits_memory_bytes
  - kube_pod_container_resource_requests_cpu_cores
  - kube_pod_container_resource_requests_memory_bytes
  - kube_pod_container_status_restarts_total
  - kube_pod_info
  - kube_pod_labels
  - kube_pod_status_phase
  - kube_pod_status_ready
  - kube_statefulset_metadata_generation
  - kube_statefulset_replicas
  - kube_statefulset_status_observed_generation
  - kube_statefulset_status_replicas
  - kube_statefulset_status_replicas_available
  - kube_statefulset_status_replicas_ready
  - kube_statefulset_status_replicas_unavailable
  - kube_statefulset_status_replicas_updated
  - process_max_fds
  - process_open_fds
  machineControllerManager:
  - mcm_cloud_api_requests_failed_total
  - mcm_cloud_api_requests_total
  - mcm_machine_controller_frozen
  - mcm_machine_current_status_phase
  - mcm_machine_deployment_failed_machines
  - mcm_machine_items_total
  - mcm_machine_set_failed_machines
  - mcm_machinedeployment_items_total
  - mcm_machineset_items_total
  - mcm_scrape_failure_total
  - machine_adds
  - machine_depth
  - machine_queue_latency
  - machine_retries
  - machine_work_duration
  - machinedeployment_adds
  - machinedeployment_depth
  - machinedeployment_queue_latency
  - machinedeployment_retries
  - machinedeployment_work_duration
  - machinesafetyapiserver_adds
  - machinesafetyapiserver_depth
  - machinesafetyapiserver_queue_latency
  - machinesafetyapiserver_retries
  - machinesafetyapiserver_work_duration
  - machinesafetyorphanvms_adds
  - machinesafetyorphanvms_depth
  - machinesafetyorphanvms_queue_latency
  - machinesafetyorphanvms_retries
  - machinesafetyorphanvms_work_duration
  - machinesafetyovershooting_adds
  - machinesafetyovershooting_depth
  - machinesafetyovershooting_latency
  - machinesafetyovershooting_retries
  - machinesafetyovershooting_work_duration
  - machineset_adds
  - machineset_depth
  - machineset_queue_latency
  - machineset_retries
  - machineset_work_duration
  - node_adds
  - node_depth
  - node_queue_latency
  - node_retries
  - node_work_duration
  - secret_adds
  - secret_depth
  - secret_queue_latency
  - secret_retries
  - secret_work_duration
  - process_max_fds
  - process_open_fds
  nodeExporter:
  - node_cpu_seconds_total
  - node_filesystem_avail_bytes
  - node_filesystem_free_bytes
  - node_filesystem_size_bytes
  - node_load1
  - node_load5
  - node_load15
  - node_memory_Active_bytes
  - node_nf_conntrack_entries
  - node_nf_conntrack_entries_limit
  - process_max_fds
  - process_open_fds
  prometheus:
  - process_max_fds
  - process_open_fds
  - process_resident_memory_bytes
  - process_virtual_memory_bytes
  - prometheus_config_last_reload_successful
  - prometheus_engine_query_duration_seconds
  - prometheus_rule_group_duration_seconds
  - prometheus_rule_group_iterations_missed_total
  - prometheus_rule_group_iterations_total
  - prometheus_tsdb_blocks_loaded
  - prometheus_tsdb_compactions_failed_total
  - prometheus_tsdb_compactions_total
  - prometheus_tsdb_compactions_triggered_total
  - prometheus_tsdb_head_active_appenders
  - prometheus_tsdb_head_chunks
  - prometheus_tsdb_head_gc_duration_seconds
  - prometheus_tsdb_head_gc_duration_seconds_count
  - prometheus_tsdb_head_samples_appended_total
  - prometheus_tsdb_head_series
  - prometheus_tsdb_reloads_failures_total
  - prometheus_tsdb_reloads_total
  - prometheus_tsdb_wal_corruptions_total
  blackboxExporter:
  - probe_duration_seconds
  - probe_http_duration_seconds
  - probe_success
  - probe_http_status_code
  vpa:
  - vpa_status_recommendation
  - vpa_spec_container_resource_policy_allowed
  - vpa_metadata_generation
  vpn:
  - probe_http_status_code
  - probe_success
  elasticsearch:
  - elasticsearch_cluster_health_active_primary_shards
  - elasticsearch_cluster_health_active_shards
  - elasticsearch_cluster_health_delayed_unassigned_shards
  - elasticsearch_cluster_health_number_of_pending_tasks
  - elasticsearch_cluster_health_status
  - elasticsearch_filesystem_data_free_bytes
  - elasticsearch_indices_flush_time_seconds
  - elasticsearch_indices_flush_total
  - elasticsearch_indices_segments_count
  - elasticsearch_indices_segments_memory_bytes
  - elasticsearch_jvm_memory_pool_used_bytes
  - elasticsearch_jvm_memory_pool_max_bytes

seed:
  apiserver: https://api.foo.bar
  region: antarctica-1
  profile: penguin

shoot:
  apiserver: https://api.foo.bar
  provider: aws

rules:
  optional:
    cluster-autoscaler:
      enabled: true
    alertmanager:
      enabled: false
    elasticsearch:
      enabled: true

ignoreAlerts: false

# object can be any object you want to scale Prometheus on:
# - number of Pods
# - number of Nodes
# - total Foos
objectCount: 4
resources:
  requests:
    cpu:
      base: 200
      perObject: 6
      weight: 5
      unit: m
    memory:
      base: 360
      perObject: 35
      weight: 5
      unit: Mi
  limits:
    cpu:
      base: 350
      perObject: 12
      weight: 5
      unit: m
    memory:
      base: 760
      perObject: 60
      weight: 5
      unit: Mi
