apiVersion: {{ include "podsecuritypolicyversion" .}}
kind: PodSecurityPolicy
metadata:
  name: gardener.kube-system.node-exporter
spec:
  privileged: false
  volumes:
  - hostPath
  hostNetwork: true
  hostPID: true
  allowedHostPaths:
  - pathPrefix: /
  - pathPrefix: /sys
  - pathPrefix: /proc
  hostPorts:
  - min: {{ .Values.ports.metrics }}
    max: {{ .Values.ports.metrics }}
  runAsUser:
    rule: 'MustRunAsNonRoot'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  readOnlyRootFilesystem: false
