apiVersion: "autoscaling.k8s.io/v1beta2"
kind: VerticalPodAutoscaler
metadata:
  name: kube-apiserver-vpa
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    apiVersion: {{ include "deploymentversion" . }}
    kind: Deployment
    name: kube-apiserver
  updatePolicy:
    updateMode: "Off"
