{{- if .Values.serviceAccountConfig }}
{{- if .Values.serviceAccountConfig.signingKey}}
---
apiVersion: v1
kind: Secret
metadata:
  name: kube-apiserver-service-account-signing-key
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  signing-key: {{ .Values.serviceAccountConfig.signingKey | b64enc }}
{{- end}}
{{- end}}
