apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-exporter-config-prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    app: prometheus
    role: monitoring
data:
  blackbox.yaml: |
    modules:
      icmp_probe:
        prober: icmp
        timeout: 5s
      tcp_vpn:
        prober: tcp
        timeout: 5s
      http_apiserver:
        prober: http
        timeout: 10s
        http:
          headers:
            Accept: "*/*"
            Accept-Language: "en-US"
          tls_config:
            ca_file: "/var/run/secrets/blackbox/ca.crt"
            cert_file: "/var/run/secrets/blackbox/prometheus.crt"
            key_file: "/var/run/secrets/blackbox/prometheus.key"
          preferred_ip_protocol: "ip4"
