rule_files:
- ../rules/apiserver-connectivity-check.rules.yaml

evaluation_interval: 30s

tests:
- interval: 30s
  input_series:
  # ApiServerUnreachableViaKubernetesService
  - series: 'probe_success{job="blackbox-exporter-k8s-service-check"}'
    values: '0+0x30'
  alert_rule_test:
  - eval_time: 15m
    alertname: ApiServerUnreachableViaKubernetesService
    exp_alerts:
    - exp_labels:
        service: apiserver-connectivity-check
        severity: critical
        type: shoot
        visibility: all
        job: blackbox-exporter-k8s-service-check
      exp_annotations:
        summary: Api server unreachable via the kubernetes service.
        description: The Api server has been unreachable for 3 minutes via the kubernetes service in the shoot.