rule_files:
- ../rules/kube-etcd3.rules.yaml

evaluation_interval: 30s

tests:
- interval: 30s
  input_series:
  # KubeEtcdMainDown
  - series: 'up{job="kube-etcd3",role="main"}'
    values: '0+0x20'
  # KubeEtcdEventsDown
  - series: 'up{job="kube-etcd3",role="events"}'
    values: '0+0x30'
  # KubeEtcd3MainNoLeader
  - series: 'etcd_server_has_leader{job="kube-etcd3",role="main"}'
    values: '0+0x20'
  # KubeEtcd3EventsNoLeader
  - series: 'etcd_server_has_leader{job="kube-etcd3",role="events"}'
    values: '0+0x30'
  # KubeEtcd3HighNumberOfFailedProposals
  - series: 'etcd_server_proposals_failed_total{job="kube-etcd3", pod="etcd"}'
    values: '0+1x81 81+0x39'
  # KubeEtcdDeltaBackupFailed
  - series: 'etcdbr_snapshot_latest_revision{job="kube-etcd3-backup-restore",role="main",kind="Incr"}'
    values: '0+1x30'
  - series: 'etcdbr_snapshot_duration_seconds_count{job="kube-etcd3-backup-restore",role="main",kind="Incr",succeeded="true"}'
    values: '0+0x30'
  # KubeEtcdFullBackupFailed
  - series: 'etcdbr_snapshot_latest_revision{job="kube-etcd3-backup-restore",role="main",kind="Full"}'
    values: '0+1x3000'
  - series: 'etcdbr_snapshot_duration_seconds_count{job="kube-etcd3-backup-restore",role="main",kind="Full",succeeded="true"}'
    values: '0+0x3000'
  alert_rule_test:
  - eval_time: 5m
    alertname: KubeEtcdMainDown
    exp_alerts:
    - exp_labels:
        service: etcd
        severity: blocker
        type: seed
        visibility: operator
      exp_annotations:
        description: Etcd3 cluster main is unavailable or cannot be scraped. As long as etcd3 main is down the cluster is unreachable.
        summary: Etcd3 main cluster down.
  - eval_time: 15m
    alertname: KubeEtcdEventsDown
    exp_alerts:
    - exp_labels:
        service: etcd
        severity: critical
        type: seed
        visibility: operator
      exp_annotations:
        description: Etcd3 cluster events is unavailable or cannot be scraped. Cluster events cannot be collected.
        summary: Etcd3 events cluster down.
  - eval_time: 10m
    alertname: KubeEtcd3MainNoLeader
    exp_alerts:
    - exp_labels:
        service: etcd
        severity: critical
        type: seed
        visibility: operator
      exp_annotations:
        description: Etcd3 main has no leader. No communication with etcd main possible. Apiserver is read only.
        summary: Etcd3 main has no leader.
  - eval_time: 15m
    alertname: KubeEtcd3EventsNoLeader
    exp_alerts:
    - exp_labels:
        service: etcd
        severity: critical
        type: seed
        visibility: operator
      exp_annotations:
        description: Etcd3 events has no leader. No communication with etcd events possible. New cluster events cannot be collected. Events can only be read.
        summary: Etcd3 events has no leader.
  - eval_time: 1h
    alertname: KubeEtcd3HighNumberOfFailedProposals
    exp_alerts:
    - exp_labels:
        service: etcd
        severity: warning
        type: seed
        visibility: operator
        pod: etcd
        job: kube-etcd3
      exp_annotations:
        description: Etcd3 pod etcd has seen 81 proposal failures within the last hour.
        summary: High number of failed etcd proposals
  - eval_time: 15m
    alertname: KubeEtcdDeltaBackupFailed
    exp_alerts:
    - exp_labels:
        service: etcd
        severity: critical
        type: seed
        role: main
        kind: Incr
        job: kube-etcd3-backup-restore  
        visibility: operator
      exp_annotations:
        description: No delta snapshot for the past 15 minutes.
        summary: Etcd delta snapshot failure.     
  - eval_time: 1455m
    alertname: KubeEtcdFullBackupFailed
    exp_alerts:
    - exp_labels:
        service: etcd
        severity: critical
        type: seed
        role: main
        visibility: operator
        kind: Full
        job: kube-etcd3-backup-restore
      exp_annotations:
        description: No full snapshot for the past 24 hours 15minutes.
        summary: Etcd full snapshot failure.     